name: Bug Report
description: File a bug report
body:
  - type: textarea
    attributes:
      label: Describe the bug
      value: |
        <!--

        >> Before getting started, please ensure there's no existing issue with the same concern!

        Please provide the following information:

        - Description: Clear and concise description of what the bug is
        - Expected Behavior: What you expected to happen
        - Environment: At least the OS, Node.js, and concurrently's versions
        - Reproduction: A way to reproduce the issue

        Our time to work on this project is limited.
        With an accurate report you're helping us to understand and solve the request faster.
        Please understand that reports that do not meet the requirements may be closed without further notice.

        Thank you!

        -->
    validations:
      required: true
