name: Bug Report
description: File a bug report
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!
        Before you get started, please ensure there's [no existing issue](https://github.com/open-cli-tools/concurrently/issues) with the same concern!
  - type: textarea
    attributes:
      label: Describe the Bug
      value: |
        <!--

        Please provide the following information:

        - Description: Clear and concise description of what the bug is
        - Expected Behavior: What you expected to happen
        - Environment: At least the OS, Node.js, and concurrently's versions
        - Reproduction: A way to reproduce the issue

        Our time to work on this project is limited.
        With an accurate report you're helping us to understand and solve the request faster.
        Please understand that reports that do not meet the requirements may be closed without further notice.

        Thank you!

        -->
    validations:
      required: true
