name: Feature Request
description: Open a feature request
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this feature request!
        Before you get started, please ensure there's [no existing issue](https://github.com/open-cli-tools/concurrently/issues) with the same concern!
  - type: textarea
    attributes:
      label: Describe the Feature Request
      value: |
        <!--

        Please provide the following information:

        - Description: Clear and concise description of what you want
        - Use Case: Why is this needed and what is a use case for it

        Our time to work on this project is limited.
        With an accurate report you're helping us to understand and solve the request faster.
        Please understand that reports that do not meet the requirements may be closed without further notice.

        Thank you!

        -->
    validations:
      required: true
