name: Feature Request
description: Open a feature request
body:
  - type: textarea
    attributes:
      label: Describe the feature request
      value: |
        <!--

        >> Before getting started, please ensure there's no existing issue with the same concern!

        Please provide the following information:

        - Description: Clear and concise description of what you want
        - Use Case: Why is this needed and what is a use case for it

        Our time to work on this project is limited.
        With an accurate report you're helping us to understand and solve the request faster.
        Please understand that reports that do not meet the requirements may be closed without further notice.

        Thank you!

        -->
    validations:
      required: true
